openapi: 3.0.1
info:
  title: Komer Web-API
  description: This is komer web-api
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - description: Localhost server for testing API
    url: http://localhost:1904/web-api

tags:
- name: groups
- name: users
- name: recipes

paths:
  /users:
    post:
      tags:
      - users
      summary: creates a new user
      description: creates a new user to the system
      operationId: createUser
      parameters: 
        - name: name
        required: true
        schema:
          type: string
      requestBody:
        description: User to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: false
      responses:
        201:
          description: user created
          content:
            application/json:
              schema:
                required:
                - token
                type: object
                properties:
                  token:
                    type: string
                    format: uuid
        400:
          description: Invalid input, object invalid
          content: {}
      x-codegen-request-body-name: user
  /groups:
    get:
      tags:
      - groups
      summary: lists all groups
      description: lists all groups
      operationId: getGroups
      security:
        - bearerAuth: []
      parameters:
      - name: token
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Groups'
        400:
          description: bad input parameter
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
    post:
      tags:
      - groups
      summary: creates a group
      description: creates a group
      operationId: createGroup
      security:
        - bearerAuth: []
      parameters:
      - name: token
        in: header
        required: true
        schema:
          type: string
          format: uuid
      - name: name
        in: query
        description: name of the group
        required: true
        schema:
          type: string
      - name: desc
        in: query
        description: description of the group
        required: false
        schema:
          type: string
      requestBody:
        description: creates a group
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Groups'
        required: false
      responses:
        201:
          description: Group created
          content: {}
        400:
          description: Invalid input, object invalid
          content: {}
      x-codegen-request-body-name: groups
  /groups/{groupId}:
    get:
      tags:
      - groups
      summary: Get details of a group given its id
      description: Get details of a group given its id
      operationId: getDetailsFromGroup
      security:
        - bearerAuth: []
      parameters:
      - name: token
        in: header
        schema:
          type: string
          format: uuid
      - name: id
        in: path
        description: ID of the group that to be fetched
        required: true
        schema:
          type: integer
          minimum: 1
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Groups'
        400:
          description: Invalid ID supplied
          content: 
            application/json:
              schema: 
                type: string
                example: Invalid ID supplied
        404:
          description: Group not found
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/InvalidRequest'
                example: Group Not found
    put:
      tags:
      - groups
      summary: updates a group
      description: updates a group in the system
      operationId: updateGroup
      security:
        - bearerAuth: []
      parameters:
      - name: token
        in: header
        required: true
        schema:
          type: string
          format: uuid
      - name: id
        in: path
        description: ID of the group to be edited
        required: true
        schema:
          type: integer
      - name: name
        in: query
        description: name of the group
        required: true
        schema:
          type: string
      - name: desc
        in: query
        description: description of the group
        required: false
        schema:
          type: string
      requestBody:
        description: Group to edit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Groups'
        required: false
      responses:
        201:
          description: group edited
          content: {}
        404:
          description: group not found
          content: {}
    delete:
      tags:
      - groups
      summary: Delete a group by ID
      description: Delete a group by ID
      operationId: deleteGroup
      security:
        - bearerAuth: []
      parameters:
      - name: token
        in: header
        required: true
        schema:
          type: string
          format: uuid
      - name: id
        in: path
        description: ID of the group to be deleted
        required: true
        schema:
          type: integer
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Group not found
          content: {}

  /groups/{groupId}/recipes:
    post:
      tags:
      - groups
      summary: adds a recipe to a group given its id
      description: adds a recipe to a group given its id
      operationId: addRecipe
      security:
        - bearerAuth: []

      parameters:
      - name: token
        in: header
        required: true
        schema:
          type: string
          format: uuid
      - name: id
        in: path
        description: ID of the group to be deleted
        required: true
        schema:
          type: integer
      - name: name
        in: query
        description: name of the group
        required: true
        schema:
          type: string  
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Group not found
          content: {}

  /groups/{groupId}/recipes/{recipeName}:
    delete:
      tags:
        - groups
      summary: deletes a recipe (given its name) of a group given its id
      description: deletes a recipe (given its name) of a group given its id
      operationId: deleteRecipe
      security:
        - bearerAuth: []
      parameters:
      - name: token
        in: header
        required: true
        schema:
          type: string
          format: uuid
      - name: id
        in: path
        description: ID of the group to be deleted
        required: true
        schema:
          type: integer
      - name: name
        in: query
        description: name of the group
        required: true
        schema:
          type: string
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Group not found
          content: {}

  /popular:
    get:
      tags:
        - popular
      summary: Gets popular recipes from spoonnacular 
      description: Gets popular recipes from spoonnacular 
      operationId: getPopularRecipes
      security:
        - bearerAuth: []

  /search/{recipeName}:
    get:
      tags:
        - searched
      summary: Gets a recipe with the given name
      description: Gets a recipe with the given name
      operationId: searchRecipes
      security:
        - bearerAuth: []
      parameters:
      - name: name
        in: query
        description: name of the group
        required: true
        schema:
          type: string
      responses:
        400:
          description: Invalid name supplied
          content: {}
        404:
          description: recipe not found
          content: {}


components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
  schemas:
    CreateUser: 
      required:
        - name
      type: object
      properties:
        id: 
          type: integer
          example: 1
        name: 
          type: string
          example: john
        authToken:
          type: string
          example: 3232-33232-43434-4343434
    Groups:
      required:
      - token
      - id
      - name
      type: object
      properties:
        token:
          type: string
          format: uuid
        id:
          type: integer
          example: 1
        name:
          type: string
          example: fifa
        description:
          type: string
          example: Fifa game description
    NewGroup: 
      required:
      - name
      properties:
        token:
          type: string
          format: uuid
        id:
          type: integer
          example: 1
        name:
          type: string
          example: fifa
        description:
          type: string
          example: Fifa game description
    NewRecipe:
      required:
      - recipeId
      properties:
        token:
          type: string
          format: uuid
        id:
          type: integer
          example: 1
    InvalidRequest:
      type: object
      properties:
        cause:
          type: string
          example: "Missing required parameter"